### PR TITLE
NETBEANSINFRA-187 Bug netbeansinfra 187

### PR DESCRIPTION
**Pull request by jmborer**
This PR fixes and improves several things:
1) it fixes the issue https://issues.apache.org/jira/browse/NETBEANSINFRA-187
2) it fixes the way the extra clusters are injected into a NB Platform whose name is not "netbeans"
3) replaced the hardcoded "netbeans" directory name in target/nbm by "clusters" when generating those clusters

These fixes allow now to properly work and build plugins for Netbeans based application other than than the IDE such as the VisualVM for example.

### CODE REVIEW

**Comment by ebarboni** [comment]
Hi @jmborer , there are coding style issue that make modification hard to review.  curly brackt at new line and space on parenthesis. This is 'maven style'

System.err.println(">>>>>>>>> " are for debug ? maybe use getLog().debug ( ) ?

**Comment by jmborer** [comment]
Hi Eric,

I forgot to remove some of my debugging traces. I will turn them into log.

Concerning the coding style, I was to prone to hit "reformat" in my netbeans. 

I will reformat and fix the logs and then redo a PR. 

By the way is there a Netbeans formatting profile for Maven code?

**Comment by jmborer** [comment]
I applied the coding styles recommended on: https://maven.apache.org/developers/conventions/code.html
by properly configuring my Netbeans preferences. I opened as well the Eclipse profile to determine some details to be the most compliant.

**Comment by jmborer** [comment]
Here are the preferences.
[java-maven-coding-style.zip](https://github.com/apache/netbeans-mavenutils-nbm-maven-plugin/files/4540018/java-maven-coding-style.zip)

**Comment by ebarboni** [comment]
you have mvn checkstyle:check  to have help on what is wrong, line length and method size we negledtec.

I think we can go for a NetBeans default format that will ease our work later. but once we review the ongoing PR.

**Comment by jmborer** [comment]
> you have mvn checkstyle:check to have help on what is wrong, line length and method size we negledtec.
> 
> I think we can go for a NetBeans default format that will ease our work later. but once we review the ongoing PR.

I have run check style. Well actually there are a lot of warnings that don't come from my modification. Do you want me to use the opportunity to fix them all before commit the change?

**Comment by ebarboni** [comment]
Better later to avoid confusion.

Did you link your account https://gitbox.apache.org/setup/ ?

**Comment by jmborer** [comment]
There are still a few "line too long" or "method length too long" remaining. Nothing critical IMHO.

**Comment by jmborer** [comment]
> Better later to avoid confusion.
> 
> Did you link your account https://gitbox.apache.org/setup/ ?

No. Sorry I am quite new to all this ecosystem.

**Comment by ebarboni** [comment]
your github account need to be protected by 2 factors authentication. and then you can use it. 
Once connected PMC rights (merging commit) will be available on your github.

**Comment by jmborer** [comment]
well I am using 2FA for GitHub. I have not idea why it doesn't recognise it and I double checked that I configured the proper userid on id.apache.org. Still no luck:

image

**Comment by geertjanw** [comment]
Best to file an Apache INFRA issue under GITBOX component.

**Comment by jmborer** [comment]
Do you know if there is a Jenkins build somewhere for this plugin on the Apache Infra?

**Pull request merged**
