### PR TITLE
[NETBEANSINFRA-188] Fix slow copies of module jar files

### PR DESCRIPTION
**Pull request by codingfred**
Currenty when the manifest needs to be updated the jar is copied JarEntry for JarEntry.
This is also done only byte by byte, and therefore extremely slow, even on fast drives.
This could be sped up by using a byte[] (maybe size of 8192) to copy the entries in batches.

If one looks into the source ocde for JarOuputstream, and especially the base DeflaterOutputstream,
the internal buffer is only 512 elements large and not accessible from the JarOutputStream contructor.

Instead what is done in this branch is 
1. to copy the whole jar in one go. 
2. Read the manifest from the copied jar and decide to patch it or not
3. If so just create the JarOuputStream with the modified manifest and it will get written to the jar (in the constructor) and no further JarEntries have to be touched.

In a Multi-Module based  project with several large jar files (due to contained resources) the build speed went up  by almost 50 %.
One extremely large jar saw its copy time reduced from 30 seconds down to 5 seconds (all tested on a Samsung 970 EVO nvme ssd)

I tried to match the existing coding style. The style change introduced was the usage of try-with-resources but that should not be an issue because the minimum java version supported is 1.7.

### CODE REVIEW

**Comment by codingfred** [comment]
Thanks for the hint. i ran checkstyle now and fixed all introduced whitespace remarks introduced by the code change.
Checkstyle issues on master: 165
Checkstyle issues on this pull request 166

The only one checkstyle issue left is the scope introduced to avoid polluting the parent scope with temporary variables. This scope can easily be removed if deemed unnecessary.

**Comment by jmborer** [comment]
@ebarboni: What do you think about this PR?

**Comment by jmborer** [comment]
> Thanks for the hint. i ran checkstyle now and fixed all introduced whitespace remarks introduced by the code change.
> Checkstyle issues on master: 165
> Checkstyle issues on this pull request 166
> 
> The only one checkstyle issue left is the scope introduced to avoid polluting the parent scope with temporary variables. This scope can easily be removed if deemed unnecessary.

For Maven plugins you must use the coding convention defined https://maven.apache.org/developers/conventions/code.html

What IDE are you using, because coding conventions can be greatly simplified by using IDE formatting engines? For IntelliJ and Eclipse, you can find the profiles on the link above. For Netbeans, I have published my own profile here https://github.com/apache/netbeans-mavenutils-nbm-maven-plugin/files/4540018/java-maven-coding-style.zip

**Comment by codingfred** [comment]
As recommended in https://github.com/apache/netbeans-mavenutils-nbm-maven-plugin/pull/9#issuecomment-620012695 i ran checkstyle:check and fixed all issues except the one mentioned above that were introduced by my changes.

**Comment by ebarboni** [comment]
Hi,
I guess PR it's technicaly correct but we miss a full name of contributor. 
http://netbeans.apache.org/participate/submit-pr.html#contributing-code
All commits must include the author’s full name and email address. For important modifications you will need to submit an Individual Contributor License Agreement (ICLA).

only the second commit is having good informations,  would be good to squash with good information.

**Comment by codingfred** [comment]
I interactively rebased the branch and fixed the authors information (name & email) and squashed the second commit into the first one.

**Comment by jmborer** [comment]
I have created a ticket in Jira for the traceability

**Comment by jmborer** [comment]
@codingfred: to prepare the merge, I had to fix a conflict. Can you please double check that it is still working? Thanks

**Comment by codingfred** [comment]
@jmborer I took a look but the code still looks good. However I personally think it would be cleaner to rervert the merge of the master into this branch and instead rebase this branch onto the current master. With the rebase (and fixing any conflicts that may occur) the changes that this branch introduces are easier to review.

Anyways as I said i could not observe any functional change so it should be good to go.

**Comment by codingfred** [comment]
Are there any further concerns with these changes you would like me to address?

Have a nice weekend,
Fred

**Comment by jmborer** [comment]
I have merged you PR. I'll close it on https://issues.apache.org/jira/browse/NETBEANSINFRA-188

**Pull request merged**
