### PR TITLE
asm version bump to support JDK 17.

### PR DESCRIPTION
**Pull request by mbien**
This is required to make this plugin work on JDK 17.

### CODE REVIEW

**Comment by ebarboni** [comment]
hi @mbien , bumping maven-dependency-analyzer to version 1.12 should work too.

**Comment by ebarboni** [comment]
@mbien commit - pushed on your PR. I wonder if we can use dependabot.

**Comment by mbien** [comment]
@ebarboni ah nice. The latest version of maven-dependency-analyzer depends on 9.2 too - that works. I am just usually adding the asm dep directly to have better control over it (esp in larger projects). But it should be fine in this case, assuming maven-dependency-analyzer itself bump their versions periodically (transitive dependencies in maven can be a pain).

**Comment by ebarboni** [comment]
@mbien feel free to merge.   If I remember, maven-dependency-analyzer use ASM direct dependencies if we use a too old "mda" the Opcode may be unavailable by transitive, better to bump in this case. They bump it regularly the only issue is to get a release. It can be asked on the maven dev list.

**Comment by ebarboni** [comment]
@mbien do you want me  to try release it or do you see missing improvment ?

**Comment by mbien** [comment]
@ebarboni nothing else from my side regarding this plugin.

**Pull request merged**
