### PR TITLE
First step to put all the commit back with history from the splitted repo

### PR DESCRIPTION
**Pull request by ebarboni**
I hope this is good enough. 

It's not intended to build now. (mvn clean install at root build only parent, mvn clean install in subfolder only build the individual)
Need pom rewrite and so on. Only want to regroup.

Will need to clean up in another PR (LICENSE file and so on)
Will need to tag the release commit hash again (we voted in the past) but seems everything was keep.

### CODE REVIEW

**Comment by mbien** [comment]
I see
 - nb-repository-plugin
 - nbm-maven-harness
 - nbm-shared

and nbm-maven-plugin is already in the repo. The parent plugin is no longer needed? How did you import the repos?

**Comment by ebarboni** [comment]
in the future releasing from this repo will do the parent,shared,harness,repo,nbm in one go.
after we merge this I will add the tag missing from the others repository
the repository were split from common history commit id were not changed so should be easy to track.

For the future of the no more needed repository will ask in the thread
https://issues.apache.org/jira/browse/INFRA-23373?filter=-2

**Comment by ebarboni** [comment]
will merge and make first buildable setup in a following PR

**Review by oyarzun — APPROVED** [review]
Sounds good merge in the PR so we can get to the first build

**Pull request merged**
