### PR TITLE
Revert maven-site-plugin version bump since it fails on jenkins.

### PR DESCRIPTION
**Pull request by mbien**

### CODE REVIEW

**Comment by cstamas** [comment]
Better move off M release, use 3.12.1 until real 4.0.0 is out (M releases are not even like alphas)

**Comment by mbien** [comment]
roger. wondering if we should test this on gh actions too.

**Comment by mbien** [comment]
ah! thats the reason for the M releases:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.12.1:site (default-cli) on project utilities-parent: RendererException while preparing context for skin: Cannot use skin: has 2.0.0-M7 Doxia Sitetools prerequisite, but current is 1.11.1 -> [Help 1]
```

**Comment by mbien** [comment]
reverted to M9 and added a comment

**Comment by ebarboni** [comment]
maybe bumping fluido skin could help. fluido already in M* version

**Comment by cstamas** [comment]
Yeah, I personally stay away from M site related stuff. You can track progress here, but site M releases are fragile, needs one given M as dependency, and IMO a stable project should stay away from those:
https://cwiki.apache.org/confluence/display/MAVEN/Towards+Doxia+2.0.0+Stack

**Comment by mbien** [comment]
i have no experience with the maven site plugins. I can randomly bump versions but won't be easily able if everything works/looks as expected.

M9 did work before (I assume) with the currently used skin, so i would rather leave it as is.

**Comment by cstamas** [comment]
For M releases you need to align the whole stack, moreover, it MAY work now, but will stop working tomorrow.
Again, safest is to move back to last "stable" pre-M release with all site related stuff.

**Comment by mbien** [comment]
ok, reverting to 3.x for the plugin and 1.x for the skin did work locally (`./mvnw verify site:site -P run-its`). Once jenkins stages the new site, someone please check if it looks as expected.

**Comment by cstamas** [comment]
+1 lgtm, except the comment "sensitive to fluido versions", is true for M releases, but should not be for "ordinary" (non-M) releases.

**Comment by ebarboni** [comment]
lgtm too, UI looks the same

**Pull request merged**
