### PR TITLE
[NETBEANS-2553] Let nbm:autoupdate find the same output dir that nbm:…

### PR DESCRIPTION
**Pull request by phipma**
…build-installers does.

### CODE REVIEW

**Comment by ebarboni** [comment]
@phipma will merge once iCLA check. As you mention you submitted it. Remember me if I miss.

**Comment by phipma** [comment]
Hi @ebarboni my ICLA was accepted, so please review again, thanks, Mark.

**Comment by ebarboni** [comment]
we should also think on it tests later :D

**Comment by ebarboni** [comment]
And many thanks for your contribution.

**Pull request merged**
