### PR TITLE
[NETBEANSINFRA-189]: Fix regression introduced by [NETBEANSINFRA-188]

### PR DESCRIPTION
**Pull request by codingfred**
The optimization  - implemented in #8 - introduced a serious regression
by truncating the whole jar file instead of modifying a single entry in the jar file.

This PR fixes this by applying another approach. Using the in Java 7
introduced Files API, one can create a virtual filesystem of a zip file
and read or write single entries.

In my tests the now modfied jar files are no longer truncated
and the whole module suite can be compiled and executed successfully.
The intended speedup retains.

### CODE REVIEW

**Comment by codingfred** [comment]
Currently I'm printing out and signing the Apache ICLA, so that no non-technical reasons hinder the fix of my scew up!

**Comment by ebarboni** [comment]
Hi, I'm not sure the ICLA was recieved did you mention NetBeans project so we are notified ?

**Comment by neilcsmith-net** [comment]
@ebarboni shouldn't need an ICLA for something this simple anyway.

**Comment by ebarboni** [comment]
Yep but seems important to author.

**Comment by matthiasblaesing** [comment]
The list of ICLA signees is available publicly:
Committers: https://whimsy.apache.org/public/icla-info.json
Non-Committers: https://whimsy.apache.org/public/icla-info_noid.json

**Comment by ebarboni** [comment]
@neilcsmith-net a bit for the joke, a 50 lines changes on nbm-maven-plugin is "important" compared to the same change in netbeans repo :D. 
But I misunderstand @codingfred intention of willing to have ICLA. By the way ICLA is recieved.

**Pull request merged**
